name: Test resources validation
on:
  workflow_dispatch:  # Allow manual triggering
  push:
    branches:
      - main
      - release/*
      - snapshot/*
    tags:
      - v*
  pull_request:
  merge_group:
jobs:
  test-validate-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install percli
        uses: ./actions/install_percli
        with:
          cli_version: latest

      - name: Install cue binary
        uses: perses/github-actions/actions/setup_environment@main
        with:
          enable_go: true
          enable_cue: true
          cue_version: "v0.12.0"

      - name: Test resources validation
        uses: ./actions/validate_resources
        with:
          directory: ./testdata/resources_folder

      - name: Test resources validation with file
        uses: ./actions/validate_resources
        with:
          file: ./testdata/resource.json